<?php
/**
 * AJAX OCR Worker Endpoint (process_trigger.php)
 * Runs Tesseract OCR on the uploaded image and updates database state.
 */
header('Content-Type: application/json');
require_once __DIR__ . '/config.php';

// Check auth
if (!is_logged_in()) {
    echo json_encode(['success' => false, 'error' => 'Akses ditolak. Silakan login.']);
    exit;
}

$id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
$user_id = $_SESSION['user_id'];

try {
    $db = get_db_connection();
    
    // Select and verify ownership
    $stmt = $db->prepare("SELECT * FROM uploads WHERE id = ? AND user_id = ?");
    $stmt->execute([$id, $user_id]);
    $upload = $stmt->fetch();
    
    if (!$upload) {
        echo json_encode(['success' => false, 'error' => 'Data berkas tidak ditemukan.']);
        exit;
    }

    // Set state to processing
    $stmt_proc = $db->prepare("UPDATE uploads SET status = 'processing' WHERE id = ?");
    $stmt_proc->execute([$id]);

    // Paths definitions
    $input_path = BASE_DIR . $upload['file_path'];
    $filename_without_ext = pathinfo($upload['file_name'], PATHINFO_FILENAME);
    $output_base = UPLOAD_DIR . $filename_without_ext;
    $output_txt = $output_base . '.txt';

    // Verify input file exists
    if (!file_exists($input_path)) {
        $db->prepare("UPDATE uploads SET status = 'failed' WHERE id = ?")->execute([$id]);
        echo json_encode(['success' => false, 'error' => 'Berkas gambar asli hilang di server.']);
        exit;
    }

    // Shell argument escaping
    $input_escaped = escapeshellarg($input_path);
    $output_escaped = escapeshellarg($output_base);

    // Escape binary path in case of spaces
    $tess_bin = TESSERACT_PATH;
    if (strpos($tess_bin, ' ') !== false && $tess_bin[0] !== '"') {
        $tess_bin = '"' . $tess_bin . '"';
    }

    // Tesseract Command: tesseract input output_base -l eng+ind
    $cmd = "$tess_bin $input_escaped $output_escaped -l eng+ind 2>&1";
    
    $output_lines = [];
    $return_var = -1;
    
    exec($cmd, $output_lines, $return_var);

    if ($return_var === 0) {
        if (file_exists($output_txt)) {
            $ocr_text = file_get_contents($output_txt);
            
            // Clean control characters and convert encoding to UTF-8 if necessary
            $ocr_text = mb_convert_encoding($ocr_text, 'UTF-8', 'UTF-8, ISO-8859-1');
            
            // Clean up temporary text file generated by Tesseract
            unlink($output_txt);

            // Update record as successfully converted
            $stmt_success = $db->prepare("
                UPDATE uploads 
                SET status = 'done', ocr_text = ?, result_path = ? 
                WHERE id = ?
            ");
            // Store result text file relative path
            $result_relative_path = 'uploads/' . $filename_without_ext . '.txt';
            $stmt_success->execute([$ocr_text, $result_relative_path, $id]);

            echo json_encode([
                'success' => true,
                'redirect' => 'result.php?id=' . $id
            ]);
            exit;
        } else {
            $err = 'Tesseract berjalan sukses, namun file output .txt tidak ditemukan.';
        }
    } else {
        $console_log = implode("\n", $output_lines);
        $err = "Gagal menjalankan OCR. Tesseract mengembalikan error code $return_var.\nOutput: " . substr($console_log, 0, 150);
    }

    // Update state to failed
    $stmt_fail = $db->prepare("UPDATE uploads SET status = 'failed' WHERE id = ?");
    $stmt_fail->execute([$id]);

    echo json_encode([
        'success' => false,
        'error' => $err
    ]);
    exit;

} catch (Exception $e) {
    // Database or global exception
    try {
        $db->prepare("UPDATE uploads SET status = 'failed' WHERE id = ?")->execute([$id]);
    } catch (Exception $ex) {}
    
    echo json_encode([
        'success' => false,
        'error' => 'System Exception: ' . $e->getMessage()
    ]);
    exit;
}
